[[t8code]]
arch = "x86_64"
git-tree-sha1 = "adf7ff59e2f86482c8c0580ef50dd2153c59d883"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[t8code.download]]
    sha256 = "a39628015d8dc70bed46c9b2857ba1ba7afa883831f2aef0c53d9b61fb13ce6d"
    url = "https://github.com/staticfloat/t8code_jll.jl/releases/download/t8code-v1.1.2+4/t8code.v1.1.2.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
