[[t8code]]
arch = "x86_64"
git-tree-sha1 = "8c6f1dd797bcd97efb530ed04fd71e337a71e8e4"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[t8code.download]]
    sha256 = "1c91512b34af579ceefa47a26589844ef09bff1fd80f98c9dfdaac0378fc3167"
    url = "https://github.com/staticfloat/t8code_jll.jl/releases/download/t8code-v1.1.2+4/t8code.v1.1.2.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
