[[t8code]]
arch = "x86_64"
git-tree-sha1 = "7645ed79d93ae5e1d8a93fe5abad048b7ecfd4a8"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[t8code.download]]
    sha256 = "c488c8ea484983bf4aea5a9096d0a6e9abe4545570b0641a771f63cbb4039065"
    url = "https://github.com/staticfloat/t8code_jll.jl/releases/download/t8code-v1.1.2+4/t8code.v1.1.2.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
